export const CONTRACT_ADDRESS = "0x6c4973bc99b479e6d2A61026f63BE860591344d1";

export const MATIC_CHAIN_ID_TESTNET = "0x13881";
export const MATIC_CHAIN_NAME_TESTNET = "Mumbai";
export const MATIC_RPC_URL_TESTNET =
  "https://public.stackup.sh/api/v1/node/polygon-mumbai";
export const MATIC_BLOCK_EXPLORER_URL_TESTNET =
  "https://mumbai.polygonscan.com/";

export const listOfRaffle = [
  {
    id: 1,
    title: "Rifa do Iphone 12",
    status: "Em andamento",
    totalTickets: 100,
    ticketsSold: 50,
    ticketPrice: "0",
    totalReward: "10",
    drawDate: "2021-10-10",
    isFinished: false,
    progressWidth: 50,
  },
  {
    id: 3,
    title: "Rifa do Playstation 5",
    status: "Em andamento",
    totalTickets: 50,
    ticketsSold: 25,
    ticketPrice: "20",
    totalReward: "10",
    drawDate: "2021-12-15",
    isFinished: false,
    progressWidth: 50,
  },
  {
    id: 4,
    title: "Rifa do Drone DJI Mavic Air 2",
    status: "Em andamento",
    totalTickets: 75,
    ticketsSold: 60,
    ticketPrice: "5",
    totalReward: "10",
    drawDate: "2022-01-20",
    isFinished: false,
    progressWidth: 80,
  },
  {
    id: 5,
    title: "Rifa do Macbook Pro",
    status: "Em andamento",
    totalTickets: 200,
    ticketsSold: 100,
    ticketPrice: "20",
    totalReward: "10",
    drawDate: "2022-03-05",
    isFinished: false,
    progressWidth: 50,
  },
  {
    id: 6,
    title: "Rifa do Samsung Galaxy S21",
    status: "Em andamento",
    totalTickets: 150,
    ticketsSold: 80,
    ticketPrice: "15",
    totalReward: "10",
    drawDate: "2022-04-10",
    isFinished: false,
    progressWidth: 53,
  },
  {
    id: 7,
    title: "Rifa do Drone DJI Mini 2",
    status: "Em andamento",
    totalTickets: 50,
    ticketsSold: 25,
    ticketPrice: "10",
    totalReward: "10",
    drawDate: "2022-05-15",
    isFinished: false,
    progressWidth: 50,
  },
  {
    id: 8,
    title: "Rifa do Nintendo Switch",
    status: "Em andamento",
    totalTickets: 80,
    ticketsSold: 70,
    ticketPrice: "10",
    totalReward: "10",
    drawDate: "2022-06-20",
    isFinished: false,
    progressWidth: 88,
  },
  {
    id: 9,
    title: "Rifa da TV LG 4K",
    status: "Finalizada",
    totalTickets: 120,
    ticketsSold: 120,
    ticketPrice: "8",
    totalReward: "10",
    drawDate: "2021-11-30",
    isFinished: true,
    progressWidth: 100,
  },
  {
    id: 10,
    title: "Rifa do Oculus Quest 2",
    status: "Finalizada",
    totalTickets: 80,
    ticketsSold: 80,
    ticketPrice: "15",
    totalReward: "10",
    drawDate: "2022-01-10",
    isFinished: true,
    progressWidth: 100,
  },
  {
    id: 11,
    title: "Rifa da Bicicleta Elétrica",
    status: "Finalizada",
    totalTickets: 50,
    ticketsSold: 40,
    ticketPrice: "10",
    totalReward: "10",
    drawDate: "2022-02-28",
    isFinished: true,
    progressWidth: 80,
  },
  {
    id: 12,
    title: "Rifa do Drone DJI Phantom 4",
    status: "Finalizada",
    totalTickets: 30,
    ticketsSold: 30,
    ticketPrice: "25",
    totalReward: "10",
    drawDate: "2022-03-15",
    isFinished: true,
    progressWidth: 100,
  },
  {
    id: 13,
    title: "Rifa do Apple Watch Series 7",
    status: "Finalizada",
    totalTickets: 100,
    ticketsSold: 90,
    ticketPrice: "12",
    totalReward: "10",
    drawDate: "2022-04-05",
    isFinished: true,
    progressWidth: 90,
  },
  {
    id: 14,
    title: "Rifa do Smartphone Xiaomi Mi 11",
    status: "Finalizada",
    totalTickets: 150,
    ticketsSold: 140,
    ticketPrice: "10",
    totalReward: "10",
    drawDate: "2022-05-20",
    isFinished: true,
    progressWidth: 93,
  },
  {
    id: 15,
    title: "Rifa do Headset Gaming",
    status: "Finalizada",
    totalTickets: 60,
    ticketsSold: 55,
    ticketPrice: "8",
    totalReward: "10",
    drawDate: "2022-06-10",
    isFinished: true,
    progressWidth: 92,
  },
];
